export { parsePatch, parsePatches } from './parse.js'
export { validatePatch, validatePatches } from './validate.js'
export { renderUnifiedDiff, renderPatchSummary } from './render.js'
export { enforcePatchPolicy } from './severity-enforcement.js'
export type { ParseResult } from './parse.js'
export type { ValidationResult, ValidationReason } from './validate.js'
export type { EnforcementResult, EnforcementRecord } from './severity-enforcement.js'
